# function to apply upset queries that select all intersections with one ore more terms

# function that takes the data, sets, and minimum intersection size for the upset plot data,
# plus a vector of strings matching one or more sets, and returns a vector of every intersection
# for the given upset plot that contains at least one of those sets

define_query_intersections <- function(data, sets, min_size = 0,  sets_to_query) {
  intersections <- unique(upset_data(data, sets, min_size)$plot_intersections_subset)
  intersection_query_by_set <- paste(sets_to_query, collapse = "|")
  queried_intersections <- intersections[str_detect(intersections, intersection_query_by_set)]
  return(queried_intersections)
}

test <- define_query_intersections(rosmap_boolean_categories, 
                                   sortedUpsetCategories, 
                                   min_size = 30,
                                   sets_to_query = c("peripheral metabolomics", "monocyte bulk RNAseq"))


# generate the query list to pass to the upset plot function

# this function takes a vector of intersection queries generated by define_intersection_queries(),
# color, fill, and other optional upset_query() parameters and returns a list that can be passed to
# `queries = ` in the upset plot
generate_upset_query_list <- function(intersection_queries, color, fill, set = NULL, group_by_group = NULL, only_components = NULL) {
  query_list <- map(intersection_queries,
                    ~list(set = set,
                          intersect = str_replace(unlist(str_split(.x, "-")), "_", "-"),
                          group_by_group = group_by_group,
                          only_components = only_components,
                          color = color,
                          fill = fill)
    
  )
  return(query_list)
}

test_list <- generate_upset_query_list(test, color = "blue", fill = "blue")

# test plot

upset(
  rosmap_boolean_categories,
  rev(sortedUpsetCategories),
  min_size = 30,
  queries = test_list
)

